name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: syntaximos
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - uses: actions/checkout@v2
    - uses: actions/checkout@v1
    - name: Set who I am
      run: |
        git config --global user.email "desilvakdn2@gmail.com"
        git config --global user.name "desilvakdn"
        git config --global url."git@github.com:".insteadOf "https://github.com/"
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/fiverrmateapi/myserver1
          git pull origin main
          git status
          npm install i
          pm2 restart index.js
